server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

            - id: RESUME-SERVICE
              uri: lb://RESUME-SERVICE
              predicates:
                - Path=/api/resume/**

            - id: PORTFOLIO-SERVICE
              uri: lb://PORTFOLIO-SERVICE
              predicates:
                - Path=/api/portfolio/**
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 30   
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 60   

