server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 30   
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 60   

